In [1]:
import numpy as np
import pandas as pd


np.random.seed(20)
in_file = 'train.csv'
full_data = pd.read_csv(in_file)
full_data.head()

id                species   margin1   margin2   margin3   margin4  \
0   1            Acer_Opalus  0.007812  0.023438  0.023438  0.003906   
1   2  Pterocarya_Stenoptera  0.005859  0.000000  0.031250  0.015625   
2   3   Quercus_Hartwissiana  0.005859  0.009766  0.019531  0.007812   
3   5        Tilia_Tomentosa  0.000000  0.003906  0.023438  0.005859   
4   6     Quercus_Variabilis  0.005859  0.003906  0.048828  0.009766   

    margin5   margin6   margin7  margin8    ...      texture55  texture56  \
0  0.011719  0.009766  0.027344      0.0    ...       0.007812   0.000000   
1  0.025391  0.001953  0.019531      0.0    ...       0.000977   0.000000   
2  0.003906  0.005859  0.068359      0.0    ...       0.154300   0.000000   
3  0.021484  0.019531  0.023438      0.0    ...       0.000000   0.000977   
4  0.013672  0.015625  0.005859      0.0    ...       0.096680   0.000000   

   texture57  texture58  texture59  texture60  texture61  texture62  \
0   0.002930   0.002930   0.035156        0.0        0.0   0.004883   
1   0.000000   0.000977   0.023438        0.0        0.0   0.000977   
2   0.005859   0.000977   0.007812        0.0        0.0   0.000000   
3   0.000000   0.000000   0.020508        0.0        0.0   0.017578   
4   0.021484   0.000000   0.000000        0.0        0.0   0.000000   

   texture63  texture64  
0   0.000000   0.025391  
1   0.039062   0.022461  
2   0.020508   0.002930  
3   0.000000   0.047852  
4   0.000000   0.031250  

[5 rows x 194 columns]

In [2]:
full_data.describe()

id     margin1     margin2     margin3     margin4  \
count   990.000000  990.000000  990.000000  990.000000  990.000000   
mean    799.595960    0.017412    0.028539    0.031988    0.023280   
std     452.477568    0.019739    0.038855    0.025847    0.028411   
min       1.000000    0.000000    0.000000    0.000000    0.000000   
25%     415.250000    0.001953    0.001953    0.013672    0.005859   
50%     802.500000    0.009766    0.011719    0.025391    0.013672   
75%    1195.500000    0.025391    0.041016    0.044922    0.029297   
max    1584.000000    0.087891    0.205080    0.156250    0.169920   

          margin5     margin6     margin7     margin8     margin9     ...      \
count  990.000000  990.000000  990.000000  990.000000  990.000000     ...       
mean     0.014264    0.038579    0.019202    0.001083    0.007167     ...       
std      0.018390    0.052030    0.017511    0.002743    0.008933     ...       
min      0.000000    0.000000    0.000000    0.000000    0.000000     ...       
25%      0.001953    0.000000    0.005859    0.000000    0.001953     ...       
50%      0.007812    0.015625    0.015625    0.000000    0.005859     ...       
75%      0.017578    0.056153    0.029297    0.000000    0.007812     ...       
max      0.111330    0.310550    0.091797    0.031250    0.076172     ...       

        texture55   texture56   texture57   texture58   texture59   texture60  \
count  990.000000  990.000000  990.000000  990.000000  990.000000  990.000000   
mean     0.036501    0.005024    0.015944    0.011586    0.016108    0.014017   
std      0.063403    0.019321    0.023214    0.025040    0.015335    0.060151   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000977    0.000000    0.004883    0.000000   
50%      0.004883    0.000000    0.005859    0.000977    0.012695    0.000000   
75%      0.043701    0.000000    0.022217    0.009766    0.021484    0.000000   
max      0.429690    0.202150    0.172850    0.200200    0.106450    0.578130   

        texture61   texture62   texture63   texture64  
count  990.000000  990.000000  990.000000  990.000000  
mean     0.002688    0.020291    0.008989    0.019420  
std      0.011415    0.039040    0.013791    0.022768  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000977  
50%      0.000000    0.003906    0.002930    0.011719  
75%      0.000000    0.023438    0.012695    0.029297  
max      0.151370    0.375980    0.086914    0.141600  

[8 rows x 193 columns]

In [3]:
full_data.isnull().any()

id           False
species      False
margin1      False
margin2      False
margin3      False
margin4      False
margin5      False
margin6      False
margin7      False
margin8      False
margin9      False
margin10     False
margin11     False
margin12     False
margin13     False
margin14     False
margin15     False
margin16     False
margin17     False
margin18     False
margin19     False
margin20     False
margin21     False
margin22     False
margin23     False
margin24     False
margin25     False
margin26     False
margin27     False
margin28     False
             ...  
texture35    False
texture36    False
texture37    False
texture38    False
texture39    False
texture40    False
texture41    False
texture42    False
texture43    False
texture44    False
texture45    False
texture46    False
texture47    False
texture48    False
texture49    False
texture50    False
texture51    False
texture52    False
texture53    False
texture54    False
texture55    False
texture56   

In [2]:
x_train = full_data.drop(['id', 'species'], axis=1).values

In [10]:
x_train

array([[ 0.007812,  0.023438,  0.023438, ...,  0.004883,  0.      ,
         0.025391],
       [ 0.005859,  0.      ,  0.03125 , ...,  0.000977,  0.039062,
         0.022461],
       [ 0.005859,  0.009766,  0.019531, ...,  0.      ,  0.020508,
         0.00293 ],
       ..., 
       [ 0.001953,  0.003906,  0.      , ...,  0.027344,  0.      ,
         0.001953],
       [ 0.      ,  0.      ,  0.046875, ...,  0.      ,  0.001953,
         0.00293 ],
       [ 0.023438,  0.019531,  0.03125 , ...,  0.023438,  0.025391,
         0.022461]])

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

le = LabelEncoder().fit(full_data['species'])
y_train = le.transform(full_data['species'])

In [13]:
y_train

array([ 3, 49, 65, 94, 84, 40, 54, 78, 53, 89, 98, 16, 74, 50, 58, 31, 43,
        4, 75, 44, 83, 84, 13, 66, 15,  6, 73, 22, 73, 31, 36, 27, 94, 88,
       12, 28, 21, 25, 20, 60, 84, 65, 69, 58, 23, 76, 18, 52, 54,  9, 48,
       47, 64, 81, 83, 36, 58, 21, 81, 20, 62, 88, 34, 92, 79, 82, 20, 32,
        4, 84, 36, 35, 72, 60, 71, 72, 52, 50, 54, 11, 51, 18, 47,  5,  8,
       37, 97, 20, 33,  1, 59,  1, 56,  1,  9, 57, 20, 79, 29, 16, 32, 54,
       93, 10, 46, 59, 84, 76, 15, 10, 15,  0, 69,  4, 51, 51, 94, 36, 39,
       62,  2, 24, 26, 35, 25, 87,  0, 55, 34, 38,  1, 45,  7, 93, 56, 38,
       21, 51, 75, 81, 74, 33, 20, 37,  9, 40, 60, 31, 83, 50, 71, 67, 30,
       66,  1, 43, 61, 23, 65, 84, 87, 46, 57, 16,  2, 28, 12, 96, 44, 76,
       29, 75, 41, 87, 67, 61, 30,  5, 12, 62,  3, 83, 81,  6, 85,  4, 37,
       57, 84, 39, 71, 61,  6, 76, 14, 31, 98, 40, 17, 51, 16, 42, 63, 86,
       37, 69, 86, 71, 80, 78, 14, 35, 25,  5, 39,  8,  9, 26, 44, 60, 13,
       14, 77, 13, 80, 87

In [4]:
scaler = StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)

In [15]:
x_train

array([[-0.48661074, -0.13135701, -0.33095592, ..., -0.39487147,
        -0.65214311,  0.26239707],
       [-0.58560191, -0.73488047, -0.02856115, ..., -0.49497401,
         2.18166976,  0.13364087],
       [-0.58560191, -0.48340807, -0.48219201, ..., -0.52001246,
         0.83564129, -0.72463124],
       ..., 
       [-0.78358426, -0.63430181, -1.23821765, ...,  0.1807566 ,
        -0.65214311, -0.76756462],
       [-0.88257543, -0.73488047,  0.5762671 , ..., -0.52001246,
        -0.51045972, -0.72463124],
       [ 0.30542003, -0.23196142, -0.02856115, ...,  0.08065405,
         1.18988604,  0.13364087]])

In [5]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [6]:
test = pd.read_csv('test.csv')
test_ids = test.pop('id')
x_test = test.values
scaler = StandardScaler().fit(x_test)
x_test = scaler.transform(x_test)
y_test = clf.predict_proba(x_test)

In [18]:
y_test

array([[ 0.00298946,  0.00535666,  0.0016286 , ...,  0.00063026,
         0.00450254,  0.00053538],
       [ 0.00080149,  0.00092682,  0.00252069, ...,  0.02822409,
         0.00254936,  0.00407505],
       [ 0.00085261,  0.43285761,  0.00775348, ...,  0.00216388,
         0.00643474,  0.02584805],
       ..., 
       [ 0.00184338,  0.00307004,  0.00520036, ...,  0.00276469,
         0.00116199,  0.00153281],
       [ 0.0073834 ,  0.00237959,  0.00485862, ...,  0.00304135,
         0.00288962,  0.0016284 ],
       [ 0.00100606,  0.00398832,  0.00407172, ...,  0.00063265,
         0.00143324,  0.00750655]])

In [7]:
submission = pd.DataFrame(y_test, index=test_ids, columns=le.classes_)

In [8]:
submission

Acer_Capillipes  Acer_Circinatum  Acer_Mono  Acer_Opalus  Acer_Palmatum  \
id                                                                              
4            0.002989         0.005357   0.001629     0.033095       0.002258   
7            0.000801         0.000927   0.002521     0.007314       0.003596   
9            0.000853         0.432858   0.007753     0.019051       0.043364   
12           0.000267         0.042262   0.003269     0.001900       0.004010   
13           0.003995         0.001607   0.003337     0.000316       0.002352   
16           0.009685         0.002371   0.002583     0.224303       0.003799   
19           0.007969         0.004405   0.003251     0.393528       0.003365   
23           0.001486         0.005543   0.005149     0.008447       0.002417   
24           0.012036         0.006185   0.005156     0.000901       0.001244   
28           0.010023         0.004564   0.006472     0.004774       0.001804   
33           0.004442         0.001057   0.005029     0.001082       0.006111   
36           0.021738         0.002808   0.003629     0.000423       0.004218   
39           0.007325         0.001672   0.001700     0.008374       0.002925   
41           0.003697         0.002885   0.010917     0.011084       0.001418   
44           0.001295         0.001929   0.001093     0.010060       0.002991   
46           0.000247         0.009427   0.009053     0.004838       0.002348   
47           0.003165         0.003819   0.008387     0.000804       0.003419   
51           0.011274         0.008372   0.010098     0.003368       0.003626   
52           0.005739         0.003273   0.002862     0.000841       0.001693   
53           0.001680         0.008797   0.000406     0.010089       0.000950   
57           0.000873         0.002318   0.004239     0.002830       0.003436   
59           0.005183         0.001099   0.018867     0.001631       0.006988   
62           0.001939         0.004862   0.002673     0.007001       0.002990   
65           0.001645         0.000848   0.003570     0.000349       0.002490   
68           0.000241         0.587614   0.000882     0.002448       0.006388   
70           0.000783         0.001834   0.003789     0.000629       0.004618   
74           0.001387         0.002274   0.002431     0.002448       0.003558   
77           0.001428         0.002659   0.000960     0.008990       0.002958   
79           0.016647         0.004992   0.002335     0.001903       0.004103   
86           0.001861         0.001649   0.003449     0.000607       0.003933   
...               ...              ...        ...          ...            ...   
1493         0.001289         0.026837   0.004412     0.002071       0.006027   
1495         0.004880         0.001903   0.003587     0.000464       0.004539   
1497         0.026606         0.010496   0.004060     0.002660       0.008638   
1498         0.002163         0.003537   0.004687     0.003908       0.002696   
1503         0.017411         0.003784   0.002313     0.001551       0.002231   
1510         0.006425         0.001973   0.002529     0.000049       0.003266   
1513         0.003265         0.001521   0.001118     0.004394       0.003114   
1517         0.000739         0.003227   0.001991     0.001984       0.001992   
1522         0.004904         0.000432   0.004766     0.002992       0.003116   
1526         0.001588         0.002280   0.004323     0.004086       0.001557   
1528         0.005770         0.003367   0.000897     0.003846       0.002377   
1533         0.002192         0.001065   0.001439     0.007992       0.001670   
1534         0.005873         0.005552   0.002165     0.003127       0.004103   
1535         0.003210         0.008712   0.001607     0.002037       0.003560   
1537         0.005351         0.004355   0.002786     0.022320       0.002980   
1540         0.552317         0.001220   0.004818     0.000687       0.001097   
1542         0.021070         0.00251

In [9]:
submission.to_csv('Vayne2.csv')